name: Test & Validate

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate TOC file
        run: |
          echo "Validating TOC file..."
          
          # Check if TOC file exists
          if [ ! -f "PvPProfile.toc" ]; then
            echo "❌ TOC file not found!"
            exit 1
          fi
          
          # Check required fields
          grep -q "^## Interface:" PvPProfile.toc || { echo "❌ Missing Interface field"; exit 1; }
          grep -q "^## Title:" PvPProfile.toc || { echo "❌ Missing Title field"; exit 1; }
          grep -q "^## Version:" PvPProfile.toc || { echo "❌ Missing Version field"; exit 1; }
          grep -q "^## Author:" PvPProfile.toc || { echo "❌ Missing Author field"; exit 1; }
          
          echo "✅ TOC file validation passed"

      - name: Validate Lua syntax
        run: |
          echo "Installing luacheck..."
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

          echo "Running luacheck on Lua files..."
          if ! luacheck src/; then
            echo "::error:: Lua syntax validation failed. Please fix the issues before releasing."
            exit 1
          fi

      - name: Validate file structure
        run: |
          echo "Validating project structure..."
          
          # Check core files exist
          test -f "PvPProfile.toc" || { echo "❌ Missing TOC file"; exit 1; }
          test -f "CHANGELOG.md" || { echo "❌ Missing CHANGELOG.md"; exit 1; }
          test -f "README.md" || { echo "❌ Missing README.md"; exit 1; }
          test -d "src/" || { echo "❌ Missing src/ directory"; exit 1; }
          
          # Check for common Lua files
          test -f "src/core.lua" || { echo "❌ Missing core.lua"; exit 1; }
          
          echo "✅ File structure validation passed"

      - name: Test package creation
        run: |
          echo "Testing package creation..."
          
          # Create a test package
          mkdir -p test-release/PvPProfile
          cp PvPProfile.toc test-release/PvPProfile/
          cp -r src/ test-release/PvPProfile/
          
          # Create test archive
          cd test-release
          zip -r ../test-package.zip PvPProfile/
          cd ..
          
          # Verify archive contents
          unzip -l test-package.zip
          
          echo "✅ Package creation test passed"

      - name: Validate version consistency
        run: |
          echo "Checking version consistency..."
          
          # Extract version from TOC
          TOC_VERSION=$(grep "^## Version:" PvPProfile.toc | cut -d: -f2 | tr -d ' ')
          echo "TOC Version: $TOC_VERSION"
          
          # Check if CHANGELOG mentions this version
          if grep -q "## \[$TOC_VERSION\]" CHANGELOG.md; then
            echo "✅ Version $TOC_VERSION found in CHANGELOG"
          else
            echo "ℹ️  Version $TOC_VERSION not yet in CHANGELOG (may be in Unreleased)"
          fi

  lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Lint GitHub Actions workflows
        run: |
          echo "Validating GitHub Actions workflow syntax..."
          
          # Basic YAML syntax check
          python3 -c "
          import yaml
          import sys
          
          workflow_files = ['.github/workflows/release.yml', '.github/workflows/test.yml']
          
          for file in workflow_files:
              try:
                  with open(file, 'r') as f:
                      yaml.safe_load(f)
                  print(f'✅ {file} syntax is valid')
              except yaml.YAMLError as e:
                  print(f'❌ {file} has YAML syntax error: {e}')
                  sys.exit(1)
              except FileNotFoundError:
                  print(f'⚠️  {file} not found')
          " || exit 1 